# 퓨처스리그 항공

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.linear_model import LinearRegression, Ridge, Lasso, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import matplotlib.pyplot as  plt
import mglearn

In [3]:
AFSNT = pd.read_csv("AFSNT.csv", engine='python')          # train table

AFSNT_DLY = pd.read_csv("AFSNT_DLY.csv", engine='python')   # Target table

SFSNT = pd.read_csv("SFSNT.csv", engine='python')       # 비행기의 요일별 출항유무

In [4]:
AFSNT.info()

SFSNT.info()

AFSNT.describe()

SFSNT.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987709 entries, 0 to 987708
Data columns (total 17 columns):
SDT_YY    987709 non-null int64
SDT_MM    987709 non-null int64
SDT_DD    987709 non-null int64
SDT_DY    987709 non-null object
ARP       987709 non-null object
ODP       987709 non-null object
FLO       987709 non-null object
FLT       987709 non-null object
REG       987251 non-null object
AOD       987709 non-null object
IRR       987709 non-null object
STT       987709 non-null object
ATT       979461 non-null object
DLY       987709 non-null object
DRR       119917 non-null object
CNL       987709 non-null object
CNR       3018 non-null object
dtypes: int64(3), object(14)
memory usage: 128.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 17 columns):
SSC    1171 non-null object
FLT    1171 non-null object
ORG    1171 non-null object
DES    1171 non-null object
STD    1153 non-null object
STA    1152 non-null object
FLO    1171 non-null object
MON    750 non-null object
TUE    745 non-null object
WED    739 non-null object
THU    741 non-null object
FRI    744 non-null object
SAT    743 non-null object
SUN    722 non-null object
FSD    1171 non-null int64
FED    1171 non-null int64
IRR    1171 non-null object
dtypes: int64(2), object(15)
memory usage: 155.6+ KB

                FSD           FED
count  1.171000e+03  1.171000e+03
mean   2.019049e+07  2.019097e+07
std    1.978824e+02  1.063757e+02
min    2.019033e+07  2.019070e+07
25%    2.019033e+07  2.019102e+07
50%    2.019040e+07  2.019103e+07
75%    2.019063e+07  2.019103e+07
max    2.019092e+07  2.019103e+07

In [5]:
AFSNT.head()

,SDT_YY,SDT_MM,SDT_DD,SDT_DY,ARP,ODP,FLO,FLT,REG,AOD,IRR,STT,ATT,DLY,DRR,CNL,CNR
0,2017,1,1,일,ARP1,ARP3,A,A1901,SEw3Nzc2,D,N,6:10,6:18,N,NaN,N,NaN
1,2017,1,1,일,ARP1,ARP3,A,A1905,SEw4MjM2,D,N,6:15,6:25,N,NaN,N,NaN
2,2017,1,1,일,ARP1,ARP3,L,L1751,SEw4MjM3,D,N,6:20,6:30,N,NaN,N,NaN
3,2017,1,1,일,ARP1,ARP3,F,F1201,SEw4MjA3,D,N,6:25,6:34,N,NaN,N,NaN
4,2017,1,1,일,ARP3,ARP1,A,A1900,SEw3NzAz,D,N,6:30,6:37,N,NaN,N,NaN

In [6]:
len(AFSNT)

987709

In [28]:
AFSNT[(AFSNT["DLY"] == "Y") | (AFSNT["CNL"] == "Y")]["ARP"].value_counts()

ARP3     61432
ARP1     34902
ARP2     12958
ARP6      4137
ARP8      4024
ARP4      3675
ARP15     1797
ARP5      1146
ARP9      1062
ARP13      782
ARP12      530
ARP11      351
ARP7       211
ARP14      188
ARP10        1
Name: ARP, dtype: int64

In [54]:
AFSNT["ARP"].value_counts()

ARP3     393607
ARP1     310665
ARP2     121513
ARP6      34472
ARP4      33623
ARP8      33195
ARP5      16321
ARP15     13696
ARP9      12759
ARP12      4880
ARP13      4248
ARP11      3658
ARP7       3163
ARP14      1897
ARP10        12
Name: ARP, dtype: int64

In [17]:
AFSNT["ODP"].value_counts()

ARP3     393429
ARP1     308825
ARP2     121030
ARP6      34427
ARP4      33515
ARP8      33191
ARP15     16383
ARP5      16318
ARP9      12761
ARP12      4877
ARP13      4248
ARP11      3653
ARP7       3149
ARP14      1896
ARP10         7
Name: ODP, dtype: int64

In [18]:
AFSNT["FLO"].value_counts()

J    276447
A    177187
B    135235
H    131935
I     95074
F     88110
L     83712
C         3
D         2
K         2
E         1
G         1
Name: FLO, dtype: int64

In [19]:
AFSNT["FLT"].value_counts()

L1804     1832
L1805     1828
L1807     1828
L1808     1828
J1534     1826
L1806     1826
A1736     1824
J1911     1824
F1703     1822
A1233     1822
J1806     1822
B1029     1822
A1198     1822
J1535     1822
I1320     1822
J1416     1822
A1234     1822
J1910     1822
F1701     1822
J1808     1822
H1705     1822
B1207     1822
J1637     1822
A1735     1822
L1906     1822
J1814     1822
H1513     1822
B1021     1822
J1006     1822
J1334     1822
          ...
A1336A       1
A1459        1
I1954        1
A1511        1
J1077D       1
B1041        1
J1493        1
A1861A       1
H1591        1
F1594F       1
B1803M       1
J1495        1
F1268F       1
A1107A       1
J1478        1
H1594        1
G1095A       1
A1123A       1
L1005        1
A1463        1
J1931        1
J1148F       1
J1800        1
A1858A       1
F1504F       1
F1153F       1
H1941M       1
A1862A       1
H1793        1
J1135T       1
Name: FLT, Length: 1541, dtype: int64

In [80]:
AFSNT["AOD"].value_counts()

A    493992
D    493717
Name: AOD, dtype: int64

## 분석할 카피본 만들기

In [107]:
Test = AFSNT.copy()

In [112]:
Test.drop(["SDT_YY", "SDT_DD", "SDT_MM", "REG", "IRR", "STT", "ATT"], axis = 1, inplace = True)

In [36]:
Test[(Test["DLY"] == "Y") | (Test["CNL"] == "Y")]

       SDT_DY    ARP    ODP FLO     FLT AOD DLY  DRR CNL  CNR
7           일   ARP1   ARP3   A   A1907   D   Y  C01   N  NaN
24          일   ARP2   ARP3   I   I1561   D   Y  C02   N  NaN
48          일   ARP3   ARP1   A   A1907   A   Y  C01   N  NaN
75          일   ARP2   ARP3   H   H1503   D   Y  D01   N  NaN
87          일   ARP3   ARP1   H   H1102   D   Y  C02   N  NaN
91          일  ARP15   ARP2   J   J1404   D   Y  D01   N  NaN
105         일   ARP3   ARP1   A   A1906   D   Y  C02   N  NaN
111         일   ARP3   ARP1   I   I1306   D   Y  C02   N  NaN
152         일   ARP2   ARP3   H   H1505   D   Y  C02   N  NaN
154         일   ARP4   ARP3   L   L1803   D   Y  C01   N  NaN
157         일   ARP3   ARP1   A   A1954   D   Y  C01   N  NaN
184         일   ARP1   ARP3   A   A1906   A   Y  C02   N  NaN
191         일   ARP3   ARP1   H   H1104   D   Y  C02   N  NaN
231         일   ARP1   ARP3   A   A1915   D   Y  C02   N  NaN
235         일   ARP3   ARP4   L   L1803   A   Y  C01   N  NaN
239         일   ARP1   ARP3   F   F1209   D   Y  C02   N  NaN
245         일   ARP1   ARP3   A   A1954   A   Y  C01   N  NaN
248         일   ARP2  ARP15   J   J1409   D   Y  C02   N  NaN
256         일   ARP3   ARP2   B   B1104   D   Y  C02   N  NaN
258         일   ARP3   ARP8   L   L1904   D   Y  C02   N  NaN
291         일   ARP1   ARP3   A   A1983   D   Y  C02   N  NaN
304         일   ARP3   ARP1   A   A1915   A   Y  C02   N  NaN
315         일   ARP1   ARP3   H   H1113   D   Y  C02   N  NaN
346         일   ARP8   ARP3   L   L1905   D   Y  C02   N  NaN
351         일   ARP3   ARP1   A   A1914   D   Y  C02   N  NaN
355         일   ARP3  ARP13   F   F1302   D   Y  C02   N  NaN
356         일   ARP1   ARP3   A   A1921   D   Y  C02   N  NaN
396         일   ARP3   ARP1   L   L1764   D   Y  C02   N  NaN
425         일   ARP1   ARP3   A   A1914   A   Y  C02   N  NaN
426         일   ARP3   ARP1   A   A1984   D   Y  C02   N  NaN
...       ...    ...    ...  ..     ...  ..  ..  ...  ..  ...
987510      일   ARP1   ARP3   A   A1991   D   Y  C02   N  NaN
987520      일   ARP1   ARP3   F   F1231   D   Y  C02   N  NaN
987529      일   ARP3  ARP12   A   A1182   D   Y  C02   N  NaN
987531      일  ARP15   ARP2   J   J1410   D   Y  C03   N  NaN
987535      일   ARP1   ARP3   F   F1226   A   Y  C01   N  NaN
987538      일   ARP1   ARP3   I   I1339   D   Y  C02   N  NaN
987539      일   ARP4   ARP3   L   L1809   D   Y  C02   N  NaN
987545      일   ARP2   ARP1   H  H1961F   D   Y  C02   N  NaN
987548      일   ARP1   ARP3   F   F1233   D   Y  C02   N  NaN
987554      일   ARP3   ARP4   B   B1206   D   Y  C02   N  NaN
987558      일  ARP12   ARP1   J   J1637   D   Y  C02   N  NaN
987559      일   ARP3   ARP2   B   B1118   D   Y  C02   N  NaN
987577      일   ARP3   ARP1   A   A1985   A   Y  C02   N  NaN
987596      일  ARP12   ARP3   A   A1182   A   Y  C02   N  NaN
987608      일   ARP3   ARP6   A   A1236   D   Y  C02   N  NaN
987614      일   ARP2   ARP1   J   J1129   D   Y  C02   N  NaN
987626      일   ARP3   ARP1   A   A1994   D   Y  C02   N  NaN
987633      일   ARP3   ARP1   F   F1233   A   Y  C02   N  NaN
987634      일   ARP3   ARP1   A   A1996   D   Y  C02   N  NaN
987638      일   ARP4   ARP3   B   B1206   A   Y  C02   N  NaN
987646      일   ARP3   ARP2   J   J1021   D   Y  C02   N  NaN
987654      일  ARP12   ARP3   A   A1181   D   Y  C02   N  NaN
987655      일   ARP3   ARP1   A   A1998   D   Y  C02   N  NaN
987659      일   ARP3   ARP4   L   L1810   D   Y  C02   N  NaN
987661      일   ARP3   ARP1   F   F1232   D   Y  C02   N  NaN
987664      일   ARP3   ARP1   H   H1134   D   Y  C02   N  NaN
987665      일   ARP3   ARP1   F   F1282   D   Y  C02   N  NaN
987670      일   ARP3   ARP6   I   I1560   D   Y  C02   N  NaN
987685      일   ARP1   ARP3   A   A1994   A   Y  C02   N  NaN
987686      일   ARP3  ARP12   A   A1181   A   Y  C02   N  NaN

[127196 rows x 10 columns]

In [87]:
Test0 = Test.copy()

In [137]:
Test[(Test["DLY"] == "Y") | (Test["CNL"] == "Y")]["DLYCNL"] = 1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [147]:
Test.loc[(Test["DLY"] == "Y") | (Test["CNL"] == "Y") , ["DLYCNL"] ] = 1

In [88]:
Test1 = Test0[["ARP", "DLY", "CNL"]]

Test2 = Test0[["ODP", "DLY", "CNL"]]

Test3 = Test0[["FLO", "DLY", "CNL"]]

Test4 = Test0[["FLT", "DLY", "CNL"]]

In [150]:
Test.loc[ Test["DLYCNL"] != 1 , ["DLYCNL"] ] = 0

In [152]:
Test.drop(["DLY", "CNL"], axis = 1 , inplace = True)

In [153]:
Test

         ARP    ODP FLO     FLT AOD DLYCNL
0       ARP1   ARP3   A   A1901   D      0
1       ARP1   ARP3   A   A1905   D      0
2       ARP1   ARP3   L   L1751   D      0
3       ARP1   ARP3   F   F1201   D      0
4       ARP3   ARP1   A   A1900   D      0
5       ARP1   ARP3   H   H1101   D      0
6       ARP1   ARP3   I   I1301   D      0
7       ARP1   ARP3   A   A1907   D      1
8       ARP1   ARP3   I   I1303   D      0
9       ARP1   ARP3   J   J1204   D      0
10      ARP1   ARP3   A   A1903   D      0
11      ARP7   ARP3   L   L1931   D      0
12      ARP3   ARP1   J   J1203   D      0
13      ARP1  ARP12   J   J1634   D      0
14      ARP4  ARP15   J   J1415   D      0
15      ARP1   ARP3   B   B1011   D      0
16      ARP2   ARP3   B   B1101   D      0
17      ARP3   ARP1   A   A1928   D      0
18      ARP2  ARP15   A   A1532   D      0
19      ARP3   ARP1   I   I1302   D      0
20      ARP1   ARP3   L   L1701   D      0
21      ARP2  ARP15   J   J1405   D      0
22      ARP2   ARP4   B  B1808F   D      0
23      ARP1   ARP3   F   F1203   D      0
24      ARP2   ARP3   I   I1561   D      1
25      ARP2   ARP3   J   J1004   D      0
26      ARP3   ARP1   J   J1253   D      0
27      ARP3   ARP1   A   A1901   A      0
28      ARP1   ARP3   B   B1013   D      0
29      ARP1   ARP3   A   A1981   D      0
...      ...    ...  ..     ...  ..    ...
987679  ARP7   ARP3   A   A1168   A      0
987680  ARP1   ARP3   L   L1734   A      0
987681  ARP6   ARP3   A   A1236   A      0
987682  ARP3   ARP1   H   H1147   A      0
987683  ARP1   ARP2   B   B1828   A      0
987684  ARP1   ARP3   J   J1265   A      0
987685  ARP1   ARP3   A   A1994   A      1
987686  ARP3  ARP12   A   A1181   A      1
987687  ARP1   ARP3   H   H1128   A      0
987688  ARP1   ARP3   I   I1340   A      0
987689  ARP2   ARP3   J   J1021   A      0
987690  ARP1   ARP3   A   A1996   A      0
987691  ARP3   ARP1   J   J1268   A      0
987692  ARP4   ARP3   L   L1810   A      0
987693  ARP1   ARP3   J   J1267   A      0
987694  ARP1   ARP3   H   H1130   A      0
987695  ARP1   ARP3   I   I1336   A      0
987696  ARP1   ARP3   L   L1736   A      0
987697  ARP1   ARP3   A   A1998   A      0
987698  ARP1   ARP3   H   H1158   A      0
987699  ARP1   ARP3   I   I1338   A      0
987700  ARP1   ARP2   B   B1830   A      0
987701  ARP6   ARP3   F   F1706   A      0
987702  ARP1   ARP3   F   F1232   A      0
987703  ARP1   ARP3   B   B1014   A      0
987704  ARP3   ARP1   A   A1995   A      0
987705  ARP1   ARP3   H   H1134   A      0
987706  ARP2   ARP1   B   B1831   A      0
987707  ARP1   ARP3   F   F1282   A      0
987708  ARP6   ARP3   I   I1560   A      0

[987709 rows x 6 columns]

## Sklearn 을 이용한 분석

In [154]:
le = LabelEncoder()

In [155]:
LabelTest = Test.copy()

In [209]:
X = LabelTest.iloc[:, :-1].values

In [252]:
LabelTest

       ARP ODP FLO   FLT AOD DLYCNL
0        0   8   0   234   1      0
1        0   8   0   238   1      0
2        0   8  11  1494   1      0
3        0   8   5   544   1      0
4        8   0   0   233   1      0
5        0   8   7   697   1      0
6        0   8   8   924   1      0
7        0   8   0   240   1      1
8        0   8   8   926   1      0
9        0   8   9  1171   1      0
10       0   8   0   236   1      0
11      12   8  11  1539   1      0
12       8   0   9  1170   1      0
13       0   3   9  1332   1      0
14       9   6   9  1270   1      0
15       0   8   1   331   1      0
16       7   8   1   367   1      0
17       8   0   0   261   1      0
18       7   6   0   137   1      0
19       8   0   8   925   1      0
20       0   8  11  1448   1      0
21       7   6   9  1261   1      0
22       7   9   1   474   1      0
23       0   8   5   546   1      0
24       7   8   8   989   1      1
25       7   8   9  1050   1      0
26       8   0   9  1220   1      0
27       8   0   0   234   0      0
28       0   8   1   333   1      0
29       0   8   0   313   1      0
...     ..  ..  ..   ...  ..    ...
987679  12   8   0    35   0      0
987680   0   8  11  1481   0      0
987681  11   8   0    60   0      0
987682   8   0   7   734   0      0
987683   0   7   1   497   0      0
987684   0   8   9  1232   0      0
987685   0   8   0   325   0      1
987686   8   3   0    47   0      1
987687   0   8   7   722   0      0
987688   0   8   8   962   0      0
987689   7   8   9  1067   0      0
987690   0   8   0   327   0      0
987691   8   0   9  1235   0      0
987692   9   8  11  1518   0      0
987693   0   8   9  1234   0      0
987694   0   8   7   724   0      0
987695   0   8   8   959   0      0
987696   0   8  11  1483   0      0
987697   0   8   0   329   0      0
987698   0   8   7   741   0      0
987699   0   8   8   960   0      0
987700   0   7   1   499   0      0
987701  11   8   5   663   0      0
987702   0   8   5   577   0      0
987703   0   8   1   334   0      0
987704   8   0   0   326   0      0
987705   0   8   7   726   0      0
987706   7   0   1   500   0      0
987707   0   8   5   619   0      0
987708  11   8   8   987   0      0

[987709 rows x 6 columns]

In [253]:
knn = KNeighborsClassifier()

In [265]:
KnnTest = LabelTest.astype(int)

In [266]:
x_train, x_test, y_train, y_test = train_test_split(KnnTest.iloc[:,:-1], KnnTest.iloc[:,-1])

In [267]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [268]:
np.mean(knn.predict(x_test) == y_test.values)

0.8572215382621655

In [269]:
knn.score(x_test, y_test)

0.8572215382621655

In [272]:
knn.predict(x_test)

array([0, 0, 0, ..., 0, 1, 0])

In [275]:
for x in range(1,11):
    knn = KNeighborsClassifier(n_neighbors=x)
    knn.fit(x_train, y_train)
    print(knn.score(x_test, y_test))

0.8017357286334478
0.8604087021317955
0.8474818570595477
0.8646893021447547
0.8572215382621655
0.8658313354500097
0.8628385602280827
0.8670989114235729
0.8642276291064602
0.8682976414177412

In [285]:
for x in range(11,20):
    knn = KNeighborsClassifier(n_neighbors=x)
    knn.fit(x_train, y_train)
    print(knn.score(x_test, y_test))

0.8651833732909998
0.8696016652627486
0.8668397265599689
0.8683745869241236
0.8675889328063241
0.8699985420851423
0.8694072766150457
0.8702455776582647
0.8698487008358712

In [289]:
lr = LinearRegression().fit(x_train, y_train)

In [291]:
lr.score(x_train, y_train)

0.026423626066398254

In [292]:
lr.score(x_test, y_test)

0.02726731550216599

In [294]:
ridge = Ridge().fit(x_train, y_train)

In [296]:
ridge.score(x_train, y_train)

0.026423626065655622

In [295]:
ridge.score(x_test, y_test)

0.027267311519786785

In [304]:
lasso = Lasso().fit(x_train, y_train)

print(lasso.score(x_train, y_train))

lasso.score(x_test, y_test)

0.0

-3.1250824150674816e-10

In [337]:
logistic = LogisticRegression(C=100).fit(x_train, y_train)

print(logistic.score(x_train, y_train))

logistic.score(x_test, y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

0.8712196992093479

0.8712256204237673

In [347]:
for x in range(2 ,10):
    tree = DecisionTreeClassifier(max_depth= x,random_state=0)
    tree.fit(x_train, y_train)
    print(x, tree.score(x_train, y_train))
    print(tree.score(x_test, y_test))

2 0.8712196992093479
0.8712256204237673
3 0.8712196992093479
0.8712256204237673
4 0.8712196992093479
0.8712256204237673
5 0.8713641413589172
0.8713552128555693
6 0.8713708909920745
0.871359262619063
7 0.8714194883508082
0.8714524071794207
8 0.8714545864432268
0.8713997602540011
9 0.8715018338753289
0.871403810017495

In [348]:
tree.feature_importances_

array([0.147094  , 0.02992122, 0.00055049, 0.39297041, 0.42946387])

In [351]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
print(rf.score(x_train, y_train))
print(rf.score(x_test, y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.8725007795826297
0.8716953929890494

In [352]:
rf.feature_importances_

array([0.08661135, 0.04704907, 0.03136761, 0.55282844, 0.28214352])

In [354]:
rf = MLPClassifier()
rf.fit(x_train, y_train)
print(rf.score(x_train, y_train))
print(rf.score(x_test, y_test))

0.8712210491359794
0.871229670187261

In [357]:
rfP = Perceptron()
rfP.fit(x_train, y_train)
print(rfP.score(x_train, y_train))
print(rfP.score(x_test, y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)

0.8697131810886078
0.8700511890105618

In [359]:
gbrt = GradientBoostingClassifier()
gbrt.fit(x_train, y_train)
print(gbrt.score(x_train, y_train))
print(gbrt.score(x_test, y_test))

0.8712196992093479
0.871229670187261

In [ ]:
sc = SVC()
sc.fit(x_train, y_train)
print(sc.score(x_train, y_train))
print(sc.score(x_test, y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [ ]:
lsc = LinearSVC()
lsc.fit(x_train, y_train)
print(lsc.score(x_train, y_train))
print(lsc.score(x_test, y_test))

In [ ]:
gbrt.predict_proba(X_test)

In [ ]:
Test3

## 상세하게 나눈 전처리

In [76]:
b =((Test["CNR"] != 'A05') & (Test["CNR"] != 'A01') & (Test["CNR"] != 'A02') &(Test["CNR"] != 'A07') & (Test["CNR"] != 'A03') & (Test["CNR"] != 'A10') & (Test["CNR"] != 'A99')& (Test["CNR"] != 'A09') & (Test["CNR"] != 'A04')).sum()

In [75]:
a = ((Test["DRR"] != 'A05') & (Test["DRR"] != 'A01') & (Test["DRR"] != 'A02') & (Test["DRR"] != 'A07') & (Test["DRR"] != 'A03') & (Test["DRR"] != 'A10') & (Test["DRR"] != 'A99') & (Test["DRR"] != 'A09') & (Test["DRR"] != 'A04') & (Test["DRR"] != 'A06'))

In [108]:
Test["DLYCNL"] = 0

In [136]:
Test.loc[((Test["DLY"] == "Y") & (a)) | ((Test["CNL"] == "Y") & (b)) , ["DLYCNL"] ] = 1

KeyError: 'DLY'

In [117]:
Test.drop(["DRR", "DLY", "CNL", "CNR"], axis=1, inplace=True)

In [42]:
Test["CNR"].value_counts()

A05    839
C02    642
A01    467
A02    306
A07    257
C01    198
B08    107
B03     66
Z99     32
A03     30
A10     24
A99     15
A09      8
C10      6
B06      6
C06      5
A04      4
Z01      3
C14      2
C03      1
Name: CNR, dtype: int64

In [41]:
Test["DRR"].value_counts()

C02    108578
C01      2042
A01      1543
C10      1237
D01       957
C03       913
C14       879
Z99       669
A05       608
B01       418
A02       393
C04       318
C11       190
A10       164
A99       141
B03       137
C05       122
C09       106
A07        77
A09        72
C06        67
A04        49
C13        43
C16        36
Z01        35
A03        33
D03        32
A06        27
C07         5
C15         5
B08         5
C12         4
B07         3
B06         3
B04         3
B02         2
C17         1
Name: DRR, dtype: int64

In [177]:
Test1 = Test.drop("FLT", axis =1)

In [178]:
Test_dummie = pd.get_dummies(Test1.iloc[:, :-1])

In [179]:
Test_dummie

,SDT_DY_금,SDT_DY_목,SDT_DY_수,SDT_DY_월,SDT_DY_일,SDT_DY_토,SDT_DY_화,ARP_ARP1,ARP_ARP10,ARP_ARP11,...,FLO_E,FLO_F,FLO_G,FLO_H,FLO_I,FLO_J,FLO_K,FLO_L,AOD_A,AOD_D
0,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,1
3,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
6,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
7,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
9,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,1
10,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
11,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
12,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
13,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,1
14,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
15,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
16,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
20,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,1
21,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
22,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
24,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
25,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
26,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
27,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
28,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
29,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987679,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
987680,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
987681,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
987682,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
987683,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
987684,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,0
987685,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
987686,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
987687,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
987688,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
987689,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
987690,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
987691,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
987692,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
987693,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,0
987694,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
987695,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
987696,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
987697,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
987698,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
987699,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
987700,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
987701,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
987702,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
987703,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
987704,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
987705,0,0,0,0,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
987706,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
987707,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
987708,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [171]:
x.shape

(987709, 1592)

In [180]:
x = Test_dummie.values
y = Test.iloc[:, -1].values

In [181]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)

In [ ]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
print("KNN")
print(knn.score(x_train, y_train))
print(knn.score(x_test, y_test))

In [155]:
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
print("KNN")
print(knn.score(x_train, y_train))
print(knn.score(x_test, y_test))

tree = DecisionTreeClassifier(max_depth= x,random_state=0)
tree.fit(x_train, y_train)
print("Tree")
print(tree.score(x_train, y_train))
print(tree.score(x_test, y_test))
print(tree.feature_importances_)

print("GBRT")
gbrt = GradientBoostingClassifier()
gbrt.fit(x_train, y_train)
print(gbrt.score(x_train, y_train))
print(gbrt.score(x_test, y_test))
print(gbrt.predict_proba(x_test))

print("Perceptron")
rfP = Perceptron()
rfP.fit(x_train, y_train)
print(rfP.score(x_train, y_train))
print(rfP.score(x_test, y_test))

print("Random")
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
print(rf.score(x_train, y_train))
print(rf.score(x_test, y_test))
print(rf.feature_importances_)

MemoryError:

In [55]:
AFSNT_DLY

,SDT_YY,SDT_MM,SDT_DD,SDT_DY,ARP,ODP,FLO,FLT,AOD,STT,DLY,DLY_RATE
0,2019,9,16,월,ARP1,ARP3,L,L1702,A,9:05,NaN,NaN
1,2019,9,16,월,ARP3,ARP1,L,L1702,D,7:55,NaN,NaN
2,2019,9,16,월,ARP1,ARP3,L,L1720,A,14:40,NaN,NaN
3,2019,9,16,월,ARP3,ARP1,L,L1720,D,13:30,NaN,NaN
4,2019,9,16,월,ARP4,ARP3,L,L1808,A,20:10,NaN,NaN
5,2019,9,16,월,ARP3,ARP4,L,L1808,D,19:10,NaN,NaN
6,2019,9,16,월,ARP3,ARP9,J,J1934,A,16:00,NaN,NaN
7,2019,9,16,월,ARP9,ARP3,J,J1934,D,15:00,NaN,NaN
8,2019,9,16,월,ARP3,ARP1,L,L1703,A,8:10,NaN,NaN
9,2019,9,16,월,ARP1,ARP3,L,L1703,D,7:00,NaN,NaN
10,2019,9,16,월,ARP3,ARP4,L,L1809,A,20:35,NaN,NaN
11,2019,9,16,월,ARP4,ARP3,L,L1809,D,19:35,NaN,NaN
12,2019,9,16,월,ARP3,ARP1,L,L1731,A,19:20,NaN,NaN
13,2019,9,16,월,ARP1,ARP3,L,L1731,D,18:10,NaN,NaN
14,2019,9,16,월,ARP9,ARP3,J,J1935,A,14:25,NaN,NaN
15,2019,9,16,월,ARP3,ARP1,L,L1705,A,9:25,NaN,NaN
16,2019,9,16,월,ARP1,ARP3,L,L1705,D,8:15,NaN,NaN
17,2019,9,16,월,ARP1,ARP3,L,L1732,A,21:05,NaN,NaN
18,2019,9,16,월,ARP3,ARP1,L,L1732,D,19:55,NaN,NaN
19,2019,9,16,월,ARP4,ARP3,L,L1810,A,22:10,NaN,NaN
20,2019,9,16,월,ARP3,ARP4,L,L1810,D,21:10,NaN,NaN
21,2019,9,16,월,ARP3,ARP9,J,J1935,D,13:25,NaN,NaN
22,2019,9,16,월,ARP3,ARP6,J,J1954,A,9:25,NaN,NaN
23,2019,9,16,월,ARP6,ARP3,J,J1954,D,8:20,NaN,NaN
24,2019,9,16,월,ARP1,ARP3,L,L1706,A,9:55,NaN,NaN
25,2019,9,16,월,ARP3,ARP1,L,L1706,D,8:45,NaN,NaN
26,2019,9,16,월,ARP3,ARP1,L,L1733,A,19:35,NaN,NaN
27,2019,9,16,월,ARP1,ARP3,L,L1733,D,18:25,NaN,NaN
28,2019,9,16,월,ARP3,ARP8,L,L1901,A,10:25,NaN,NaN
29,2019,9,16,월,ARP8,ARP3,L,L1901,D,9:30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16124,2019,9,30,월,ARP15,ARP4,J,J1413,A,8:05,NaN,NaN
16125,2019,9,30,월,ARP3,ARP14,J,J1856,A,10:00,NaN,NaN
16126,2019,9,30,월,ARP14,ARP3,J,J1856,D,8:50,NaN,NaN
16127,2019,9,30,월,ARP4,ARP15,J,J1413,D,6:55,NaN,NaN
16128,2019,9,30,월,ARP3,ARP13,J,J1920,A,16:25,NaN,NaN
16129,2019,9,30,월,ARP13,ARP3,J,J1920,D,15:25,NaN,NaN
16130,2019,9,30,월,ARP5,ARP3,J,J1825,A,12:55,NaN,NaN
16131,2019,9,30,월,ARP3,ARP5,J,J1825,D,11:50,NaN,NaN
16132,2019,9,30,월,ARP3,ARP12,J,J1834,A,15:40,NaN,NaN
16133,2019,9,30,월,ARP12,ARP3,J,J1834,D,14:40,NaN,NaN
16134,2019,9,30,월,ARP12,ARP3,J,J1835,A,14:00,NaN,NaN
16135,2019,9,30,월,ARP3,ARP12,J,J1835,D,13:00,NaN,NaN
16136,2019,9,30,월,ARP3,ARP14,J,J1854,A,14:30,NaN,NaN
16137,2019,9,30,월,ARP14,ARP3,J,J1854,D,13:20,NaN,NaN
16138,2019,9,30,월,ARP3,ARP8,J,J1904,A,11:00,NaN,NaN
16139,2019,9,30,월,ARP8,ARP3,J,J1904,D,10:10,NaN,NaN
16140,2019,9,30,월,ARP8,ARP3,J,J1905,A,9:35,NaN,NaN
16141,2019,9,30,월,ARP3,ARP8,J,J1905,D,8:40,NaN,NaN
16142,2019,9,30,월,ARP3,ARP8,J,J1906,A,14:25,NaN,NaN
16143,2019,9,30,월,ARP8,ARP3,J,J1906,D,13:25,NaN,NaN
16144,2019,9,30,월,ARP8,ARP3,J,J1907,A,12:50,NaN,NaN
16145,2019,9,30,월,ARP3,ARP8,J,J1907,D,11:50,NaN,NaN
16146,2019,9,30,월,ARP3,ARP8,J,J1908,A,17:45,NaN,NaN
16147,2019,9,30,월,ARP8,ARP3,J,J1908,D,16:45,NaN,NaN
16148,2019,9,30,월,ARP3,ARP8,J,J1910,A,20:25,NaN,NaN
16149,2019,9,30,월,ARP8,ARP3,J,J1910,D,19:25,NaN,NaN
16150,2019,9,30,월,ARP8,ARP3,J,J1909,A,16:10,NaN,NaN
16151,2019,9,30,월,ARP3,ARP8,J,J1909,D,15:10,NaN,NaN
16152,2019,9,30,월,ARP8,ARP3,J,J1911,A,18:50,NaN,NaN
16153,2019,9,30,월,ARP3,ARP8,J,J1911,D,17:50,NaN,NaN